name: cronjobs
type: docker-compose

services:
  app:
    image: ${DOCKER_IMAGE:-cronjobs:latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cronjobs-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      - APP_NAME=${APP_NAME:-Cronjobs.to}
      - APP_ENV=${APP_ENV:-production}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-cronjobs}
      - DB_USERNAME=${DB_USERNAME:-cronjobs}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION:-database}
      - CACHE_STORE=${CACHE_STORE:-database}
      - SESSION_DRIVER=${SESSION_DRIVER:-database}
      - MAIL_MAILER=${MAIL_MAILER:-smtp}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT:-465}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-ssl}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-Cronjobs.to}
      - AUTO_MIGRATE=${AUTO_MIGRATE:-false}
    volumes:
      - app-storage:/var/www/html/storage
      - app-bootstrap-cache:/var/www/html/bootstrap/cache
    # depends_on kaldırıldı - Dokploy'da MySQL ve Redis ayrı servisler olarak oluşturulmalı
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    #   redis:
    #     condition: service_healthy
    networks:
      - cronjobs-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MySQL ve Redis servisleri Dokploy'da ayrı servisler olarak oluşturulmalı
  # Bu yüzden burada tanımlanmamalı
  # Dokploy Dashboard → Services → MySQL ve Redis servislerini ayrı olarak oluşturun

networks:
  cronjobs-network:
    driver: bridge

volumes:
  # mysql-data ve redis-data kaldırıldı - Dokploy'da ayrı servisler kullanılıyor
  app-storage:
    driver: local
  app-bootstrap-cache:
    driver: local

